name: Conventional Commits Verification
on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  verify-commits:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify commits
        uses: opensource-nepal/commitlint@v1